LOG_ENTRY(SEVERITY,   TRACE,        (1<<__LINE__),    "[TRACE]",     LOG_COLOR_GRAY    )
LOG_ENTRY(SEVERITY,   INFO,         (1<<__LINE__),    "[INFO ]",     LOG_COLOR_GREEN   )
LOG_ENTRY(SEVERITY,   WARN,         (1<<__LINE__),    "[WARN ]",     LOG_COLOR_YELLOW  )
LOG_ENTRY(SEVERITY,   ERROR,        (1<<__LINE__),    "[ERROR]",     LOG_COLOR_RED     )
LOG_ENTRY(SEVERITY,   FATAL,        (1<<__LINE__),    "[FATAL]",     LOG_COLOR_PURPLE  )
LOG_ENTRY(SUBSYSTEM,  PLATFORM,     (1<<__LINE__),    "[PLATFORM]",  LOG_COLOR_OFF     )
LOG_ENTRY(SUBSYSTEM,  MATH,         (1<<__LINE__),    "[MATH    ]",  LOG_COLOR_CYAN    )
LOG_ENTRY(SUBSYSTEM,  MEMORY,       (1<<__LINE__),    "[MEMORY]",    LOG_COLOR_GREEN   )
LOG_ENTRY(SEVERITY,   EMPTY0,                   0,    "[     ]",     LOG_COLOR_GRAY    )
